### ISSUE TITLE
Upper-case IF causes an error

### ISSUE THREAD

**Issue by prescod** [WebsiteHQ/formula#14]
formula.compile("IF(1,2,3)")()
TypeError: this.if is not a function

**Comment by jcfisher007** [comment]
That is a bug.

https://github.com/WebsiteHQ/formula/blob/master/src/compiler.js at line 99. It needs to convert the function name to lowercase.

**Comment by jcfisher007** [comment]
Fixed in https://github.com/WebsiteHQ/formula/commit/188c394b77af6e9aa5640716b938009893befdf2
