### ISSUE TITLE
Does not support "sheet name" prefixes with quotes in them

### ISSUE THREAD

**Issue by prescod** [WebsiteHQ/formula#15]
'ab cd'!efgh

**Comment by jcfisher007** [comment]
Currently, the master branch has no support for "sheets" at all. It only supports named variables. The idea was to move away from the spreadsheet model.

Here is a link to the parser with support for sheets:

https://github.com/FormulaPages/formula-ast/blob/master/formulaParser.jison

**Comment by jcfisher007** [comment]
Perhaps something like this would work.

> require('formula/lib/parser').parse("'A B'!test")
{ type: 'variable', scope: 'A B', name: 'test' }

It would compile to code like:

context.get("A B", "test")

**Comment by prescod** [comment]
I'm a bit less concerned about the API as I am about the grammar. Can the grammar support quotes and spaces in identifier names as the old grammar did?

**Comment by jcfisher007** [comment]
Yes it can

**Comment by jcfisher007** [comment]
Fixed in https://github.com/WebsiteHQ/formula/commit/188c394b77af6e9aa5640716b938009893befdf2
